https://example.com/comments/1

###

POST http://cookie.gluehloch.de/registrationservice/api/registration/validate HTTP/1.1
content-type: application/json

{
    "name": "name",
    "nickname": "nickname",
    "firstname": "firstname",
    "email": "email@email.de",
    "password": "password",
    "applicationName": "application",
    "acceptMail": true,
    "acceptCookie": true
}

###

curl -d '{"nickname": "nickname", "name": "name", "firstname": "firstname", "email": "email@mail.de", "password": "password"}' \
   -H "Content-Type: application/json" \
  http://cookie.gluehloch.de/registrationservice/api/registration/validate

###

POST http://localhost:8080/registrationservice/api/registration/validate HTTP/1.1
content-type: application/json

{
    "name": "name",
    "nickname": "nickname22",
    "firstname": "firstname",
    "email": "email@email.de",
    "password": "password",
    "applicationName": "test",
    "acceptMail": true,
    "acceptCookie": true
}

###

POST http://192.168.99.100:9090/registrationservice/registration/validate HTTP/1.1
content-type: application/json

{
    "name": "name",
    "nickname": "nickname22",
    "firstname": "firstname",
    "email": "email@email.de",
    "password": "password",
    "applicationName": "test",
    "acceptMail": true,
    "acceptCookie": true
}

###

POST https://tippdiekistebier.de/registrationservice/registration/validate HTTP/1.1
content-type: application/json

{
    "name": "name",
    "nickname": "nickname22",
    "firstname": "firstname",
    "email": "email@email.de",
    "password": "password",
    "applicationName": "test",
    "acceptMail": true,
    "acceptCookie": true
}