CREATE DATABASE `register` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER 'register'@'localhost' IDENTIFIED BY 'register';
CREATE USER 'register'@'%' IDENTIFIED BY 'register';

CREATE USER 'registersu'@'localhost' IDENTIFIED BY 'register';
CREATE USER 'registersu'@'%' IDENTIFIED BY 'register';

REVOKE ALL PRIVILEGES ON * . * FROM 'register'@'localhost';
REVOKE ALL PRIVILEGES ON * . * FROM 'register'@'%';

REVOKE ALL PRIVILEGES ON * . * FROM 'registersu'@'localhost';
REVOKE ALL PRIVILEGES ON * . * FROM 'registersu'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE ON register.* TO 'register'@'localhost'
  WITH GRANT OPTION
  MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0
  MAX_UPDATES_PER_HOUR 0
  MAX_USER_CONNECTIONS 0;

GRANT SELECT, INSERT, UPDATE, DELETE ON register.* TO 'register'@'%'
  WITH GRANT OPTION
  MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0
  MAX_UPDATES_PER_HOUR 0
  MAX_USER_CONNECTIONS 0;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE,
  ALTER, INDEX, DROP, CREATE TEMPORARY TABLES, SHOW VIEW,
  CREATE ROUTINE, ALTER ROUTINE, EXECUTE, CREATE VIEW, EVENT, TRIGGER,
  LOCK TABLES
  ON register.* TO 'registersu'@'localhost'
  WITH GRANT OPTION
  MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0
  MAX_UPDATES_PER_HOUR 0
  MAX_USER_CONNECTIONS 0;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE,
  ALTER, INDEX, DROP, CREATE TEMPORARY TABLES, SHOW VIEW,
  CREATE ROUTINE, ALTER ROUTINE, EXECUTE, CREATE VIEW, EVENT, TRIGGER,
  LOCK TABLES
  ON register.* TO 'registersu'@'%'
  WITH GRANT OPTION
  MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0
  MAX_UPDATES_PER_HOUR 0
  MAX_USER_CONNECTIONS 0;
